<%
  require 'uri'
  default_db = File.basename(File.dirname(File.expand_path(__FILE__))).gsub("-", "_")
  uri = URI.parse(ENV["DATABASE_URL"] || "postgres://localhost/#{default_db}")
  uri_test = URI.parse(ENV["TEST_DATABASE_URL"] || "postgres://localhost/#{default_db}_test")
%>

production: &database
  <%= "adapter: #{uri.scheme == 'postgres' ? 'postgresql' : uri.scheme}" %>
  <%= "database: #{uri.path.to_s.split("/")[1]}" %>
  <%= "username: #{uri.user}" if uri.user %>
  <%= "password: #{uri.password}" if uri.password %>
  <%= "host: #{uri.host}" if uri.host && uri.host != "localhost" %>
  <%= "port: #{uri.port}" if uri.port %>
  prepared_statements: false
development: *database

test:
  <%= "adapter: #{uri_test.scheme == 'postgres' ? 'postgresql' : uri_test.scheme}" %>
  <%= "database: #{uri_test.path.to_s.split("/")[1]}" %>
  <%= "username: #{uri_test.user}" if uri_test.user %>
  <%= "password: #{uri_test.password}" if uri_test.password %>
  <%= "host: #{uri_test.host}" if uri_test.host && uri_test.host != "localhost" %>
  <%= "port: #{uri_test.port}" if uri_test.port %>
  prepared_statements: false